In [1]:
import sys, os
sys.path.append(os.pardir)  # 親ディレクトリのファイルをインポートするための設定
import numpy as np
from common import functions

def print_vec(text, vec):
    print("*** " + text + " ***")
    print(vec)

    # 【レポート提出者変更】配列のshapeを出力するよう改造
    if hasattr(vec, 'shape'):
        print("shape: " + str(vec.shape))
        
    print("")


In [2]:
# 順伝播（単層・単ユニット）

# 重み
W = np.array([[0.1], [0.2]])

print_vec("重み", W)

## 【レポート提出者変更】試してみよう_配列の初期化
W = np.zeros(2)

print_vec("重み : np.zeros(2)", W)

W = np.ones(2)

print_vec("重み : np.ones(2)", W)

W = np.random.rand(2)

print_vec("重み : np.random.rand(2)", W)

W = np.random.randint(5, size=(2))

print_vec("重み : np.random.randint(5, size=(2))", W)

# バイアス
b = 0.5

## 【レポート提出者変更】試してみよう_数値の初期化
b = np.random.rand() # 0~1のランダム数値

print_vec("バイアス : np.random.rand()", b)

b = np.random.rand() * 10 -5  # -5~5のランダム数値

print_vec("バイアス : np.random.rand() * 10 -5", b)

# 入力値
x = np.array([2, 3])
print_vec("入力", x)


# 総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.relu(u)
print_vec("中間層出力", z)


*** 重み ***
[[ 0.1]
 [ 0.2]]
shape: (2, 1)

*** 重み : np.zeros(2) ***
[ 0.  0.]
shape: (2,)

*** 重み : np.ones(2) ***
[ 1.  1.]
shape: (2,)

*** 重み : np.random.rand(2) ***
[ 0.11028877  0.17703378]
shape: (2,)

*** 重み : np.random.randint(5, size=(2)) ***
[1 4]
shape: (2,)

*** バイアス : np.random.rand() ***
0.41385335871817963

*** バイアス : np.random.rand() * 10 -5 ***
3.7220591428984537

*** 入力 ***
[2 3]
shape: (2,)

*** 総入力 ***
17.7220591429
shape: ()

*** 中間層出力 ***
17.7220591429
shape: ()



In [3]:
# 順伝播（単層・複数ユニット）

# 重み
W = np.array([
    [0.1, 0.2, 0.3], 
    [0.2, 0.3, 0.4], 
    [0.3, 0.4, 0.5],
    [0.4, 0.5, 0.6]
])

print_vec("重み", W)

## 【レポート提出者変更】試してみよう_配列の初期化
W = np.zeros((4,3))

print_vec("重み : np.zeros((4,3))", W)

W = np.ones((4,3))

print_vec("重み : np.ones((4,3))", W)

W = np.random.rand(4,3)

print_vec("重み : np.random.rand(4,3)", W)

W = np.random.randint(5, size=(4,3))

print_vec("重み : np.random.randint(5, size=(4,3))", W)

# バイアス
b = np.array([0.1, 0.2, 0.3])
print_vec("バイアス", b)

# 入力値
x = np.array([1.0, 5.0, 2.0, -1.0])
print_vec("入力", x)


#  総入力
u = np.dot(x, W) + b
print_vec("総入力", u)

# 中間層出力
z = functions.sigmoid(u)
print_vec("中間層出力", z)


*** 重み ***
[[ 0.1  0.2  0.3]
 [ 0.2  0.3  0.4]
 [ 0.3  0.4  0.5]
 [ 0.4  0.5  0.6]]
shape: (4, 3)

*** 重み : np.zeros((4,3)) ***
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
shape: (4, 3)

*** 重み : np.ones((4,3)) ***
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
shape: (4, 3)

*** 重み : np.random.rand(4,3) ***
[[ 0.26690697  0.53570994  0.62460175]
 [ 0.59134649  0.07608217  0.53408865]
 [ 0.21259075  0.04293925  0.98838637]
 [ 0.88814779  0.85585618  0.45849133]]
shape: (4, 3)

*** 重み : np.random.randint(5, size=(4,3)) ***
[[1 1 1]
 [1 1 3]
 [0 4 2]
 [4 2 2]]
shape: (4, 3)

*** バイアス ***
[ 0.1  0.2  0.3]
shape: (3,)

*** 入力 ***
[ 1.  5.  2. -1.]
shape: (4,)

*** 総入力 ***
[  2.1  12.2  18.3]
shape: (3,)

*** 中間層出力 ***
[ 0.89090318  0.99999497  0.99999999]
shape: (3,)



In [4]:
# 順伝播（3層・複数ユニット）

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")
    network = {}
    
    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成
    
    network['W1'] = np.array([
        [0.1, 0.3, 0.5],
        [0.2, 0.4, 0.6]
    ])
    network['W2'] = np.array([
        [0.1, 0.4],
        [0.2, 0.5],
        [0.3, 0.6]
    ])
    network['W3'] = np.array([
        [0.1, 0.3],
        [0.2, 0.4]
    ])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b2'] = np.array([0.1, 0.2])
    network['b3'] = np.array([1, 2])

    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("重み3", network['W3'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )
    print_vec("バイアス3", network['b3'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")

    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1
    
    # 1層の総出力
    z1 = functions.relu(u1)
    
    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 2層の総出力
    z2 = functions.relu(u2)

    # 出力層の総入力
    u3 = np.dot(z2, W3) + b3
    
    # 出力層の総出力
    y = u3
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", z1)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1, z2

# 入力値
x = np.array([1., 2.])
print_vec("入力", x)

# ネットワークの初期化
network =  init_network()

y, z1, z2 = forward(network, x)

*** 入力 ***
[ 1.  2.]
shape: (2,)

##### ネットワークの初期化 #####
*** 重み1 ***
[[ 0.1  0.3  0.5]
 [ 0.2  0.4  0.6]]
shape: (2, 3)

*** 重み2 ***
[[ 0.1  0.4]
 [ 0.2  0.5]
 [ 0.3  0.6]]
shape: (3, 2)

*** 重み3 ***
[[ 0.1  0.3]
 [ 0.2  0.4]]
shape: (2, 2)

*** バイアス1 ***
[ 0.1  0.2  0.3]
shape: (3,)

*** バイアス2 ***
[ 0.1  0.2]
shape: (2,)

*** バイアス3 ***
[1 2]
shape: (2,)

##### 順伝播開始 #####
*** 総入力1 ***
[ 0.6  1.3  2. ]
shape: (3,)

*** 中間層出力1 ***
[ 0.6  1.3  2. ]
shape: (3,)

*** 総入力2 ***
[ 1.02  2.29]
shape: (2,)

*** 出力1 ***
[ 0.6  1.3  2. ]
shape: (3,)

出力合計: 3.9


In [5]:
# 多クラス分類
# 2-3-4ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    #試してみよう
    #_各パラメータのshapeを表示
    #_ネットワークの初期値ランダム生成

    network = {}
    # 【レポート提出者変更】2x3 -> 3x5
#     network['W1'] = np.array([
#         [0.1, 0.3, 0.5],
#         [0.2, 0.4, 0.6]
#     ])
    network['W1'] = np.random.rand(3, 5)
    
    # 【レポート提出者変更】3x4 -> 5x4
#     network['W2'] = np.array([
#         [0.1, 0.4, 0.7, 1.0],
#         [0.2, 0.5, 0.8, 1.1],
#         [0.3, 0.6, 0.9, 1.2]
#     ])
    network['W2'] = np.random.rand(5, 4)
    
    # 【レポート提出者変更】1x3 -> 1x5
#     network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
    network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
# x：入力値
def forward(network, x):
    
    print("##### 順伝播開始 #####")
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    
    # 1層の総入力
    u1 = np.dot(x, W1) + b1

    # 1層の総出力
    z1 = functions.relu(u1)

    # 2層の総入力
    u2 = np.dot(z1, W2) + b2
    
    # 出力値
    y = functions.softmax(u2)
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(y)))
        
    return y, z1

## 事前データ
# 入力値
# 【レポート提出者変更】1x2 -> 1x3
# x = np.array([1., 2.])
x = np.array([1., 2., 3.])

# 目標出力
d = np.array([0, 0, 0, 1])

# ネットワークの初期化
network =  init_network()

# 出力
y, z1 = forward(network, x)

# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)



##### ネットワークの初期化 #####
*** 重み1 ***
[[ 0.21002481  0.36014637  0.92386029  0.59519304  0.3356845 ]
 [ 0.01572655  0.99350496  0.82254837  0.22953103  0.99086986]
 [ 0.51201863  0.94763694  0.6214861   0.70710944  0.24691371]]
shape: (3, 5)

*** 重み2 ***
[[ 0.70908254  0.78198883  0.66732751  0.89185961]
 [ 0.64369447  0.26810246  0.95808648  0.16768081]
 [ 0.08142008  0.80968637  0.80936507  0.74834669]
 [ 0.32004175  0.15635866  0.43153751  0.65668574]
 [ 0.56995283  0.78302445  0.28781715  0.17987138]]
shape: (5, 4)

*** バイアス1 ***
[ 0.1  0.2  0.3  0.4  0.5]
shape: (5,)

*** バイアス2 ***
[ 0.1  0.2  0.3  0.4]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[ 1.87753378  5.39006712  4.73341533  3.57558341  3.55816535]
shape: (5,)

*** 中間層出力1 ***
[ 1.87753378  5.39006712  4.73341533  3.57558341  3.55816535]
shape: (5,)

*** 総入力2 ***
[  8.45860026  10.29108648  13.11524083   9.50858979]
shape: (4,)

*** 出力1 ***
[ 0.00866635  0.05415953  0.91240897  0.02476515]
shape: (4,)

出力合計: 1.0

##### 結果表示 #

In [6]:
# 回帰
# 2-3-2ネットワーク

# ！試してみよう_ノードの構成を 3-5-4 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    # 【レポート提出者変更】 2x3 -> 3x5
#     network['W1'] = np.array([
#         [0.1, 0.3, 0.5],
#         [0.2, 0.4, 0.6]
#     ])
    network['W1'] = np.random.rand(3, 5)
    
    # 【レポート提出者変更】 3x2 -> 5x4
#     network['W2'] = np.array([
#         [0.1, 0.4],
#         [0.2, 0.5],
#         [0.3, 0.6]
#     ])
    network['W2'] = np.random.rand(5, 4)
    
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
    network['b2'] = np.array([0.1, 0.2, 0.3, 0.4])
    
    print_vec("重み1", network['W1'] )
    print_vec("重み2", network['W2'] )
    print_vec("バイアス1", network['b1'] )
    print_vec("バイアス2", network['b2'] )

    return network

# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']
    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = u2
    
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))
    
    return y, z1

# 入力値
# 【レポート提出者変更】 1x2 -> 1x3
# x = np.array([1., 2.])
x = np.array([1., 2., 3.])

network =  init_network()
y, z1 = forward(network, x)
# 目標出力
d = np.array([2., 4., 3., 1,])
# 誤差
loss = functions.mean_squared_error(d, y)
## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)


##### ネットワークの初期化 #####
*** 重み1 ***
[[ 0.71737182  0.18319503  0.06974347  0.49320441  0.28836815]
 [ 0.97223603  0.9032837   0.33392512  0.59177723  0.28302015]
 [ 0.04667915  0.06563355  0.8666638   0.01152261  0.3043866 ]]
shape: (3, 5)

*** 重み2 ***
[[ 0.63787531  0.13578147  0.00770779  0.18293024]
 [ 0.05482664  0.64308271  0.64173362  0.09822127]
 [ 0.23139468  0.87508607  0.28074091  0.21645618]
 [ 0.26927104  0.04673851  0.68002212  0.80896673]
 [ 0.37658398  0.35004249  0.70848218  0.28529531]]
shape: (5, 4)

*** バイアス1 ***
[ 0.1  0.2  0.3  0.4  0.5]
shape: (5,)

*** バイアス2 ***
[ 0.1  0.2  0.3  0.4]
shape: (4,)

##### 順伝播開始 #####
*** 総入力1 ***
[ 2.90188135  2.3866631   3.63758512  2.11132669  2.26756825]
shape: (5,)

*** 中間層出力1 ***
[ 2.90188135  2.3866631   3.63758512  2.11132669  2.26756825]
shape: (5,)

*** 総入力2 ***
[ 4.34605804  6.20446908  5.91746856  4.30756035]
shape: (4,)

*** 出力1 ***
[ 4.34605804  6.20446908  5.91746856  4.30756035]
shape: (4,)

出力合計: 13.3050245036

##### 

In [7]:
# 2値分類
# 2-3-1ネットワーク

# ！試してみよう_ノードの構成を 5-10-1 に変更してみよう

# ウェイトとバイアスを設定
# ネートワークを作成
def init_network():
    print("##### ネットワークの初期化 #####")

    network = {}
    # 【レポート提出者変更】 2x3 -> 5x10
#     network['W1'] = np.array([
#         [0.1, 0.3, 0.5],
#         [0.2, 0.4, 0.6]
#     ])
    network['W1'] = np.random.rand(5, 10)

    # 【レポート提出者変更】 3x1 -> 10x1
#     network['W2'] = np.array([
#         [0.2],
#         [0.4],
#         [0.6]
#     ])
    network['W2'] = np.random.rand(10, 1)

    # 【レポート提出者変更】 1x3 -> 1x10
#     network['b1'] = np.array([0.1, 0.2, 0.3])
    network['b1'] = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0])
    network['b2'] = np.array([0.1])
    return network


# プロセスを作成
def forward(network, x):
    print("##### 順伝播開始 #####")
    
    W1, W2 = network['W1'], network['W2']
    b1, b2 = network['b1'], network['b2']    

    # 隠れ層の総入力
    u1 = np.dot(x, W1) + b1
    # 隠れ層の総出力
    z1 = functions.relu(u1)
    # 出力層の総入力
    u2 = np.dot(z1, W2) + b2
    # 出力層の総出力
    y = functions.sigmoid(u2)
            
    print_vec("総入力1", u1)
    print_vec("中間層出力1", z1)
    print_vec("総入力2", u2)
    print_vec("出力1", y)
    print("出力合計: " + str(np.sum(z1)))

    return y, z1


# 入力値
# 【レポート提出者変更】 1x2 -> 1x5
# x = np.array([1., 2.])
x = np.array([1., 2., 3., 4., 5.])
# 目標出力
d = np.array([1])
network =  init_network()
y, z1 = forward(network, x)
# 誤差
loss = functions.cross_entropy_error(d, y)

## 表示
print("\n##### 結果表示 #####")
print_vec("中間層出力", z1)
print_vec("出力", y)
print_vec("訓練データ", d)
print_vec("誤差",  loss)

##### ネットワークの初期化 #####
##### 順伝播開始 #####
*** 総入力1 ***
[ 8.72688414  8.66035325  6.19402607  7.89952756  7.38743865  7.04442115
  6.49518361  6.67367838  8.73585367  9.67172044]
shape: (10,)

*** 中間層出力1 ***
[ 8.72688414  8.66035325  6.19402607  7.89952756  7.38743865  7.04442115
  6.49518361  6.67367838  8.73585367  9.67172044]
shape: (10,)

*** 総入力2 ***
[ 38.81387129]
shape: (1,)

*** 出力1 ***
[ 1.]
shape: (1,)

出力合計: 77.4890869184

##### 結果表示 #####
*** 中間層出力 ***
[ 8.72688414  8.66035325  6.19402607  7.89952756  7.38743865  7.04442115
  6.49518361  6.67367838  8.73585367  9.67172044]
shape: (10,)

*** 出力 ***
[ 1.]
shape: (1,)

*** 訓練データ ***
[1]
shape: (1,)

*** 誤差 ***
-9.99999950584e-08
shape: ()

